### ISSUE TITLE
תוסף שלרשת לא עובד

### ISSUE THREAD

**Issue by matanelgabsi** [cubicle-vdo/xbmc-israel#110]
התוסף של רשת לא עובד..
בדקתי למה ומסתבר שהבקשה הראשית כבר לא מקבלת תשובה.
השתמשתי בIDA וכו' על האפליציית ipad של רשת, ושיניתי את התוסף שיפעל כמוה, עכשיו זה פועל.
מצ"ב הקבצים ששיניתי כדי לגרום לזה לפעול..
http://pastebin.com/pkd52dtT - APLoader.py
http://pastebin.com/U7apFwFz - reshet.py

חוץ מזה רציתי להגיד תודה רבה! ממש כיף להשתמש בתוספים שאתם עושים פה! ואם יש משהו שאני יכול לעזור אני אשמח..

**Comment by pintolog** [comment]
כל העידכונים נעשים אוטומטית בהפעלת ה- XBMC או שאני צריך לעשות משהו על מנת
לעדכן אותם?

On Tue, Jul 1, 2014 at 11:44 AM, avigdork notifications@github.com wrote:

> תודה, התיקון נוסף.
> שלומי, אפשר לסגור, לא?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cubicle-vdo/xbmc-israel/issues/110#issuecomment-47631424
> .

##
