### ISSUE TITLE
Seretil בקשה למפתח התוסף 

### ISSUE THREAD

**Issue by itzikg** [cubicle-vdo/xbmc-israel#209]
התוסף לא עובד ונותן שגיאה האם אפשר להוציא תיקון ולעלות גרסא תקינה?

**Comment by itzikg** [comment]
??????

**Comment by avigdork** [comment]
בוצעו שינויים באתר. המפתח מודע לבעיה.
תודה.

**Comment by itzikg** [comment]
אביגדור האם יש חדש ?

**Comment by avigdork** [comment]
לפי מה שהבנתי יש בלאגן באתר, המפתח מחכה שהאתר יתייצב קצת..

**Comment by itzikg** [comment]
אוקי תודה.

**Comment by avigdork** [comment]
נראה שהאתר חזר לעבוד בצורה תקינה, בהתאם לכך התוסף חזר לתפקד.
לא נעשו שינויים בתוסף.
