### ISSUE TITLE
PlaylistLoader בקשה למפתח התוסף 

### ISSUE THREAD

**Issue by itzikg** [cubicle-vdo/xbmc-israel#212]
אני אשמח אם תוכל להכניס את זה בתוסף שלך 
*אפשרות לתמונות לליסט עצמו-להוסיף אופציה לכתוב מיקום או לבחור תמונה ממערכת הקבצים. 
*אפשרות לתמונות לערוצים בליסט-להוסיף אופציה לבחור את מיקום תיקיית הבסיס (ברשת או במערכת הקבצים) של קבצי התמונות.

**Comment by itzikg** [comment]
למה אתה לא עונה ?

**Comment by avigdork** [comment]
יש לי גם חיים אמיתיים.
כשאתפנה אטפל בזה או לפחות בחלק מזה.

**Comment by itzikg** [comment]
גם לי יש חיים אמיתיים אין קשר 
בכל אופן תודה.
