### ISSUE TITLE
Movix.ws תוסף 

### ISSUE THREAD

**Issue by itzikg** [cubicle-vdo/xbmc-israel#214]
,אביגדור שלום
כמו שאתה יודע אני בקשר ישיר עם הצוות באתר
Movix.me - עקב הבעיות לאחרונה ברגעים אלו האתר עובר לדומיין חדש
Movix.ws ו movix.byethost7.com  :שני הדומיינים הקיימים עומדים להיסגר
כתובת אחת עומדת להיסגר בימים הקרובים והשניה בהמשך 
יש מספר שינויים שצריך לעשות בתוסף 
plugin.video.movixme - לשנות את שם התוסף ל *
http://www.movix.me - ל Domain - לשנות בהגדרות את כתובת ה *
אשמח אם תעביר את זה הלאה למפתח התוסף תודה.

**Comment by vadimbrk** [comment]
לא יודע מי, לא יודע מה, כנס לגיטהאב ותשנה במקום לכתוב מיילים ארוכים.
בתאריך 2 ביוני 2015 21:18,‏ "itzik-gabay" <notifications@github.com> כתב:

**Comment by itzikg** [comment]
מי אתה אם אפשר לשאול ?

**Comment by itzikg** [comment]
בכל אופן זה לא כל כך משנה 
אני דיי חדש פה ואין לי מושג איך משנים ואיפה תודה.

**Comment by vadimbrk** [comment]
אף אחד. גם לא תורם פה באמת. רשום כדי לראות עדכונים. המפתחים אנשים עם חיים
אמיתיים ותורמים מזמנם הפנוי. לא צריך "לחפור", כשיהיה זמן ורצון, הם יעשו
לבד.
בתאריך 2 ביוני 2015 21:27,‏ "itzik-gabay" <notifications@github.com> כתב:

**Comment by itzikg** [comment]
מישהו ביקש ממך תגובה יאלה תחחפף מפה !!!

**Comment by vadimbrk** [comment]
כשאתה שם סימן שאלה בסוף המשפט אתה מבקש תגובה. חפש בגוגל "סימני פיסוק"
בתאריך 2 ביוני 2015 21:32,‏ "itzik-gabay" <notifications@github.com> כתב:

**Comment by itzikg** [comment]
.תגיד לי משעמם לך אה גזגז מפה יא טמבל

**Comment by avigdork** [comment]
יצאה גירסה עם שינויים מהמפתח.
כמו כן אני עדכנתי את שם התוסף שיתאים לשם האתר על מנת למנוע בלבול.
אין צורך לפתוח פה כל יומיים Issue.
כמו כן, זה לא פייסבוק כאן, אין מה לריב פה.
