### ISSUE TITLE
Cannot Load Settings

### ISSUE THREAD

**Issue by DJElementDC** [cubicle-vdo/xbmc-israel#218]
Used to have Israelive installed - worked perfectly. Had to reformat my cubox i4-pro from scratch with Geexbox distro. Fresh copy of XBMC 13.2 loaded. 

Installed via superrepo method remotely. I continue to get the Cannot Load Settings error even after going into Configure and choosing Defaults. Under Advanced settings, the 'Remote Settings URL' is this nonsense string of characters and not an actual URL - even after i click Defaults - could this be the issue? 

BTW - my IsraeLive version is 4.3.7

Please help! תודה :)

**Comment by DJElementDC** [comment]
Just making sure @avigdork sees this - sorry for bumping.. just driving me crazy! תודה.

**Comment by avigdork** [comment]
This is not an issue.
The "Cannot Load Settings" error shown when the addon can't download "remoteSettings.txt" from server.
You need to check if the internet connection.
Maybe there is some application or something else that blocking the address. Try to open via browser sites like: "goo.gl", "bit.ly", "copy.com", "dropbox.com"..

**Comment by DJElementDC** [comment]
This is on a standalone [cubox i4] (https://www.solid-run.com/products/cubox-i-mini-computer/cubox-i-specifications/) and internet for all other plugins and applications running works just fine. 

Is there any chance that having an older version of XBMC (13.2) make it problematic? Should I try to install an older version? It used to work fine before settings were held remotely - is that possible? Where is the remotesettings.txt hosted (full path URL?). Because the settings field has some gibberish alpha-numeric value --> sefm0Z97eLiuvaHe2pR9jaqKocjh (is this encoded or something?). 

Thanks much. Really want to get this working again! :)

**Comment by avigdork** [comment]
@DJElementDC 
Please add a link to "xbmc.log" file.
10x.

**Comment by DJElementDC** [comment]
Here's my log from restarting xbmc and loading Israelive immediately. 
http://pastebin.com/2tHjQcDK

I think the issue might have something to do with SSL certification
14:41:11 T:1701950480  NOTICE: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

Line 213 and onwards. I've heard of this issue before with other python apps on my cubox / geexbox distro....

**Comment by avigdork** [comment]
That can be a problem with SSL. Maybe the clock of your device is not tuned?
I think that the problem is in some wrong settings of the device.

**Comment by DJElementDC** [comment]
Thanks for your response Avigdor. Is there any way to simply override and hardcode the remote URL settings file? Or download the settings file and point to it locally? I realize that means if it changes I have to do this again, but I simply want it to function! I miss the app so much :(

Thanks!
Ari

**Comment by DJElementDC** [comment]
BTW - great insight about the timestamp. I've realized the time in logs changes once XBMC is loaded (XBMC pushes GMT+2) but the arch linux core time is set to GMT it seems. Maybe therefore python is using the wrong time? Could this be it?

**Comment by avigdork** [comment]
You can download the file from here:
https://github.com/avigdork/xbmc-avigdork/raw/master/remoteSettings.txt
put it in "/root/.xbmc/userdata/addon_data/plugin.video.israelive/"
But the file contains more URLs that will give you the same error.
You need to solve the SSL issue.
You need to find how to adjust the clock of Android.

**Comment by DJElementDC** [comment]
Appreciate it, @avigdork . Makes sense - all those encoded URLs will also need to be fetched. Seems I only seem to have this problem with python based scripts. 

Will keep you updated. 

Quick question - if I manually downgrade, what was the latest version that did not use remote settings? I realize it will be out of date but ultimately just using it for Israeli radio stations and CNN :)

**Comment by avigdork** [comment]
Older versions will not work..
You can put the file in the cubox folder, just to let the addon work.
Then:
- Make a fauvorites channels list on another computer.
- Export the list (from addon settings -> groups tab)
- Copy the file to the cubox.
- Go to addon settings on the cubox, and import the fouvorites list.

**Comment by avigdork** [comment]
@DJElementDC 
Did you manage to solve the problem?

**Comment by DJElementDC** [comment]
Hey Avigdor 

Unfortunately not but I'm pretty sure it has something to do with a messed up package on the geexbox distro (pyhtonSSL maybe?). I tried on a separate OS - on archlinux directly in Kodi - and it worked beautifully. 

I'm going to try and see if there are updates to anything to do with SSL / python and see if that helps fix it. 

I know sickrage, another python based git project, had lots of users with SSL verification issues so they simply enabled an option in the settings that allowed for disabling SSL verification. Might this be an option? Anything else I can try?

Thanks!

**Comment by avigdork** [comment]
I don't know.
Try to disable the SSL verification first.

**Comment by DJElementDC** [comment]
I was saying the disabling of SSL verification would have to be a setting
inside the plugin - I'm not sure how to do that within geexbox / arch linux
itself.

Anyways, i'll take another look at some point and keep you updated.
appreciate you checking in!

Thanks


On Sun, Aug 9, 2015 at 5:22 PM, Avigdor <notifications@github.com> wrote:

> I don't know.
> Try to disable the SSL verification first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cubicle-vdo/xbmc-israel/issues/218#issuecomment-129190838>
> .
>



-- 
Ari Nahmani | Kahena Digital Marketing
CEO / Founder
[image: Kahena Logo] <http://www.kahenadigital.com>
Direct:+972.52.7387882
US:+1.213.984.1235
email:ari@kahenadigital.com
web:www.kahenadigital.com
24 Derech Hevron, JVP Media Quarter
Jerusalem, Israel 93542

**Comment by DJElementDC** [comment]
I fixed it! Installed pyopenssl and it seemed to do the trick. It also
upgraded Python at the same time but I think it was the first package that
did it!

Thanks so much

On Sunday, August 9, 2015, Ari Nahmani <ari@kahenadigital.com> wrote:

> I was saying the disabling of SSL verification would have to be a setting
> inside the plugin - I'm not sure how to do that within geexbox / arch linux
> itself.
>
> Anyways, i'll take another look at some point and keep you updated.
> appreciate you checking in!
>
> Thanks
>
>
> On Sun, Aug 9, 2015 at 5:22 PM, Avigdor <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I don't know.
>> Try to disable the SSL verification first.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cubicle-vdo/xbmc-israel/issues/218#issuecomment-129190838>
>> .
>>
>
>
>
> --
> Ari Nahmani | Kahena Digital Marketing
> CEO / Founder
> [image: Kahena Logo] <http://www.kahenadigital.com>
> Direct:+972.52.7387882
> US:+1.213.984.1235
> email:ari@kahenadigital.com
> <javascript:_e(%7B%7D,'cvml','ari@kahenadigital.com');>
> web:www.kahenadigital.com
> 24 Derech Hevron, JVP Media Quarter
> Jerusalem, Israel 93542
>


-- 
Ari Nahmani | Kahena Digital Marketing
CEO / Founder
[image: Kahena Logo] <http://www.kahenadigital.com>
Direct:+972.52.7387882
US:+1.213.984.1235
email:ari@kahenadigital.com
web:www.kahenadigital.com
24 Derech Hevron, JVP Media Quarter
Jerusalem, Israel 93542

**Comment by avigdork** [comment]
:+1:

**Comment by clementbarry** [comment]
I'm getting the same error when running on... Kodi 17.0-alpha on Apple TV 4 :)
http://xbmclogs.com/ppwccIbmp#line-405

**Comment by ekrony** [comment]
I've got the same problem on the Apple TV 4.
Any idea?

**Comment by clementbarry** [comment]
I now believe this is not related to Apple TV 4. Same error occurs with Kodi 17.0-alpha on OS X 10.11. Something to do with python and SSL verification in this alpha.

**Comment by POMGames** [comment]
Any news on fixing it on Apple TV 4?
Im having the same "Cannot Load Settings" on Israelite

**Comment by avigdork** [comment]
@clementbarry, @ekrony, @POMGames.

HI, can you check version 4.8.4? I've made a bypass for the problem (there is no verifying for ssl).
You need to go to addon settings, check "Unverify SSL" (under "Show advanced settings") and restart Kodi.

**Comment by ekrony** [comment]
Working!! Thank you!

**Comment by avigdork** [comment]
Thanks.
