### ISSUE TITLE
Live Tv Israel update failed

### ISSUE THREAD

**Issue by marcianna74** [cubicle-vdo/xbmc-israel#235]
Hi!  I saw the update message for my new addon, Live Tv Israel.  It failed, any solutions for this?
Thanks.

**Comment by avigdork** [comment]
Restart Kodi. 
Install IsraeLIVE again.
Restart Kodi again.

**Comment by marcianna74** [comment]
Thank you for your quick response.  I reinstalled Israel live again over the other install as I could not find it in my video addons, The tv channels are still in my IPTV Simple client but not on my video add on list, very strange.  When I reinstalled it, I did get the message that it was enabled, but it still has not reappeared in my list of video add ons.  I've closed Kodi 3 times since then, still nothing in the list.  What could be the problem?  Thanks

**Comment by avigdork** [comment]
Try to uninstall it, restart kodi, then install it again.
If it's not working, you can try downlad and extarct the zip file in kodi-addons folder.

**Comment by marcianna74** [comment]
How would I uninstall it if I can't find the addon to click on to get to the settings in configure?

**Comment by avigdork** [comment]
System->Add-ons->Get Add-ons->.XBMC Israeli Streaming Sites->Video Add-ons

**Comment by marcianna74** [comment]
Ok, well, I finally found it in repositories strangely enough.  I uninstalled it and then reinstalled, it works, and I think I have the updated one as there are some channels that weren't there before and epgs that weren't there before.  I like this add on because there is almost no buffering as compared to other live tv addons and streams.  Thanks for your help!

**Comment by avigdork** [comment]
Enjoy.

**Comment by sergienko4** [comment]
i have a some issue. I tried to reinstall my kodi to 17v and the addon too.
But nothing helped.
I don;'t know what to do.
other addons works well.
os : ubuntu 16.04 64bit 
kodi: 17.0

**Comment by avigdork** [comment]
I know there's problem in ver 17 on iOS system (something with SSL). 
Try to check 'unverify ssl' in addon settings under advanced settings.

**Comment by sergienko4** [comment]
Hi, thank you for answering me, I didn't find anything spacial.
I did update Kodi only because i thought that will solve the problem,
However,
I check the all setting on Ubuntu bit nothing that i can see.

 *אם אתה באמת רוצה אתה תמצא דרך, אם לא אתה תמצא תרוץ*
*P*    *שומרים על איכות הסביבה **נא להימנע מהדפסת מייל זה שלא לצורך*
*.          * *P **Please consider the environment before printing this
email or any attachments.*

**Comment by greeran** [comment]
hi 
i have installed the kodi 17 with libreelec on my raspberry pi 3. i was able to install the live tv israel. I had to install it twice. on the second time it was successful but there is not israel chanel (not TV and not Radio). i installed it from the default israel.xbmc repo. could you help me solve. thanks

**Comment by ghost** [comment]
@greeran
All Israelis channels removed until the legal situation of them will be cleared.

**Comment by lemifranko** [comment]
Hi,

We have been watching the Israeli channels from kodi but with the latest update all the Israeli channels had gone. Do we have a chance to watch them? Do you know how long it will take to solve the legal situation?

Thanks
