### ISSUE TITLE
Program Data

### ISSUE THREAD

**Issue by codamans-f250** [cubicle-vdo/xbmc-israel#237]
I have 3 systems running OpenELEC 5.0.8.  One of the systems shows the program playing on many of the feeds, however the other two systems only show the feed.  I cannot find any setting differences between the systems.  Any ideas?

**Comment by codamans-f250** [comment]
Looks like it's not saving the guide data.  It say ... "Saving TV Guide" "Guide Saved" and then it does it all over again and again.

**Comment by avigdork** [comment]
Make sure you are using last version (4.4.4).
If you are using last version, please send a link for log file (kodi.log)

**Comment by avigdork** [comment]
@codamans-f250 
Hi, did you fix the problem?
