### ISSUE TITLE
Sdarot.Tv שגיאת סקריפט בתוסף 

### ISSUE THREAD

**Issue by itzikg** [cubicle-vdo/xbmc-israel#240]
,שלום
ישנה שגיאת סקריפט בכניסה לתוסף 
 http://pastebin.com/1FbgN5JJ :זה הלוג 
ישנה עוד בעיה, לאחר השינויים באתר לאחרונה
.למשתמש שתרם HD לא מציג 

.תודה

**Comment by avigdork** [comment]
@itzikg 
הועלה תיקון עבור שינויים נוספים באתר.
לפי קובץ השינויים, לא טופלה עדיין בעית ההזדהות לאתר וצפיה ב-HD

**Comment by itzikg** [comment]
תודה

**Comment by itzikg** [comment]
?HD האם מפתח התוסף יכול לבדוק את נושא האימות מול האתר וצפיה ב

**Comment by itzikg** [comment]
.האם אפשר להוסיף אפשרות לניגון טריילר לפי מה שראיתי באתר זה נמשך מיוטיוב

**Comment by itzikg** [comment]
?האם התוסף ייתמך בקודי 15 בקרוב 
הוא עובד חלקית לרוב זורק החוצה

**Comment by itzikg** [comment]
??

**Comment by itzikg** [comment]
היי 
מכיוון שאין לי מושג איך ליצור קשר עם מפתח התוסף, אני פונה אליך בבקשה לעזרה. 
דרכך אליו התוסף היום איך שהוא מהווה בעיה עבור בעלי האתר 
והם מתכוונים לחסום את הגישה אליהם לאתר דרך קודי(התוסף ייחסם) 
אחת הסיבות המרכזיות זה שאין אפשרות למשתמש להיכנס עם יוזר וסיסמה 
זה פוגע להם במוניטין והוריד להם משמעותית את כמות המנויים בחודשיים האחרונים. 
ועוד משהו בעייתי מבחינתם שהמשתמש אמור להמתין 30 שניות לפני ניגון(כמו באתר) 
עשיתי את מירב המאמצים לקשר בין המפתח לאתר וזה לא צלח 
חבל מאוד שככה הנושא יסתיים אשמח אם תחזור אלייבהקדם וננסה למצוא פיתרון לבעיה. 

תודה

**Comment by itzikg** [comment]
היי 
מכיוון שאין לי מושג איך ליצור קשר עם מפתח התוסף, אני פונה אליך בבקשה לעזרה
דרכך אליו התוסף היום איך שהוא מהווה בעיה עבור בעלי האתר 
(והם מתכוונים לחסום את הגישה אליהם לאתר דרך קודי(התוסף ייחסם
אחת הסיבות המרכזיות זה שאין אפשרות למשתמש להיכנס עם יוזר וסיסמה 
זה פוגע להם במוניטין והוריד להם משמעותית את כמות המנויים בחודשיים האחרונים
(ועוד משהו בעייתי מבחינתם שהמשתמש אמור להמתין 30 שניות לפני ניגון(כמו באתר
עשיתי את מירב המאמצים לקשר בין המפתח לאתר וזה לא צלח 
.חבל מאוד שככה הנושא יסתיים אשמח אם תחזור אלייבהקדם וננסה למצוא פיתרון לבעיה

תודה
