### ISSUE TITLE
[Request] Add NBC

### ISSUE THREAD

**Issue by KinOfMany** [cubicle-vdo/xbmc-israel#241]
Stream can be found here:

http://142.4.216.60:1935/edge/_definst_/kjgkefh6la1di6g/playlist.m3u8?wowzasessionid=1419879103

Not sure about EPG, but it's a very popular channel. Should be somewhere. You can see the channel's schedule on http://www.nbc.com/schedule or http://www.locatetv.com/listings/nbc

**Comment by avigdork** [comment]
@KinOfMany 
Hi.
The stream address have session/token key.
Do you have the site address for that stream?

**Comment by KinOfMany** [comment]
Yes and no. It's a website that hosts its' own streams, which is why they aren't taken down (and when they are it's only briefly)
http://www.stream2watch.co/

I just clicken F12 and traced the stream to that address.

**Comment by avigdork** [comment]
I've been told that this site is not reliable enough.
