### ISSUE TITLE
Movix.Me בקשה למפתח התוסף 

### ISSUE THREAD

**Issue by itzikg** [cubicle-vdo/xbmc-israel#243]
תודה רבה על העידכון...ד"א מה לגבי הדברים האחרים שרשמתי 
להוסיף בתוסף בתוך קטגוריית סרטים 
הסרטים הנצפים ביותר* 
הסרטים המדורגים ביותר* 
סרטים שנוספו לאחרונה* 
:אותו דבר בתוך קטגוריית סדרות 
הסדרות הנצפות ביותר* 
הסדרות המדורגות ביותר* 
סדרות שנוספו לאחרונה*

זאת הרשימה העדכנית ביותר לכל השרתים
http://videomega.tv/
http://vidspot.net/
https://openload.co**/
http://divxpress.com**/
http://vodlocker.com/
http://youwatch.org/
http://vidto.me/
http://goodvideohost.com/
****http://www.vidlockers.ag/ - שישים לב שרת מומלץ מאוד אבל הוא נמצא בתור הורדה למרות שהוא צפייה ישירה!! הוא תומך AC3 ואיכות HD 
http://videowood.tv/
http://vidzi.tv/
http://grifthost.com/
http://www.novamov.com/*
http://allmyvideos.net/
http://vidbull.com/
http://www.nowvideo.sx/

Api-מה לגבי ה
?סינון א'-ת' וסינון שנה לפי טווחים האם יש חדש לגבי זה

**Comment by itzikg** [comment]
התוסף כרגע לא עובד, היו שינויים באתר 
הוסיפו פרסומות לפני ניגון סרטים/סדרות

**Comment by itzikg** [comment]
תודה רבה 
?מה לגבי מה ששאלתי למעלה
אני שולח לך את רשימת השרתים המלאה חלקם חדשים שצריך להוסיף
http://videomega.tv/
http://vidspot.net/
https://openload.co**/
http://divxpress.com**/
http://vodlocker.com/
http://youwatch.org/
http://vidto.me/
http://goodvideohost.com/
*****http://www.vidlockers.ag/ - שישים לב שרת מומלץ מאוד אבל הוא נמצא בתור הורדה למרות שהוא צפייה ישירה!! הוא תומך AC3 ואיכות HD 
http://videowood.tv/
http://vidzi.tv/
http://grifthost.com**/
http://www.novamov.com/**
http://allmyvideos.net/
http://vidbull.com/
http://www.nowvideo.sx/

זאת הרשימה העדכנית ביותר לכל השרתים
יש כוכבית לאלה שחדשים

**Comment by itzikg** [comment]
מעבר לזה נוצרה קטגוריה חדשה של "הופעות חיות" אשמח אם תוסיף אותם בעמוד הראשי בתוסף
http://movix.me/genres/LiveShow
יש כרגע מעט תכנים שם 
 HD-ובקרוב יעלו עוד תכנים וגם ב

**Comment by itzikg** [comment]
URL תיקון באג של קידוד כתובת 
url = url.replace(' ', '%20')
(שורה 44) IndexPage להוסיף מתחת לפונקציה 
 נותן תוצאות חיפוש מדויקות מה שלא היה עד עכשיו

**Comment by itzikg** [comment]
indexpag הבעיה היא לא רק בחיפוש לא באופן כללי בקידוד של הכתובת. לכן המקום הכי נכון הוא בתחילת 
url = url.replace(' ', '%20')

**Comment by itzikg** [comment]
יש בעיה בניגון אוטומטי בחלק מהתכנים 
 לוג דוגמא
http://pastebin.com/jngmZvsk

**Comment by itzikg** [comment]
תודה רבה על העידכון...ד"א מה לגבי הדברים האחרים שרשמתי 
להוסיף בתוסף בתוך קטגוריית סרטים 
הסרטים הנצפים ביותר* 
הסרטים המדורגים ביותר* 
סרטים שנוספו לאחרונה* 
:אותו דבר בתוך קטגוריית סדרות 
הסדרות הנצפות ביותר* 
הסדרות המדורגות ביותר* 
סדרות שנוספו לאחרונה*

זאת הרשימה העדכנית ביותר לכל השרתים
http://videomega.tv/
http://vidspot.net/
https://openload.co**/
http://divxpress.com**/
http://vodlocker.com/
http://youwatch.org/
http://vidto.me/
http://goodvideohost.com/
****http://www.vidlockers.ag/ - שישים לב שרת מומלץ מאוד אבל הוא נמצא בתור הורדה למרות שהוא צפייה ישירה!! הוא תומך AC3 ואיכות HD 
http://videowood.tv/
http://vidzi.tv/
http://grifthost.com/
http://www.novamov.com/*
http://allmyvideos.net/
http://vidbull.com/
http://www.nowvideo.sx/

Api-מה לגבי ה
?סינון א'-ת' וסינון שנה לפי טווחים האם יש חדש לגבי זה

**Comment by itzikg** [comment]
דרך אגב משהו קטן לגבי העידכון בניגון אוטומטי 
הוא כבר לא מנגן את האיכות הטובה ביותר (דוגמא מהיר ועצבני 7) 
אם אפשר בבקשה לסדר את זה. 
_________________

**Comment by itzikg** [comment]
שני דברים שכרגע לא עובדים 
 שרת חדש לא מנגן openload 
ואי אפשר לנגן אף סדרה, בעת בחירת פרק כלשהו מתקבלת שגיאת סקריפט, נבדק אצל כמה אנשים לטיפולך מפתח ייקר.

**Comment by itzikg** [comment]
לאחר בדיקה ישנה שגיאת סקריפט 
בחלק מהשרתים וגם בניגון האוטומטי. 
מצורף לוג 
http://pastebin.com/qmxtT5pY

**Comment by itzikg** [comment]
שלום  היו שינויים באתר הורידו את הפרסומות לבינתיים כי זה עשה בעיות ,לכן אם אפשר בבקשה להוציא תיקון כי כרגע אי אפשר לנגן שום דבר תודה

**Comment by avigdork** [comment]
סודר
