### ISSUE TITLE
התוסף של רשת הפסיק לעבוד - לא מצליח לפתוח (לנגן) שום וידאו

### ISSUE THREAD

**Issue by omriamos** [cubicle-vdo/xbmc-israel#245]
לדוגמה:

23:51:51 T:796  NOTICE: DVDPlayer: Opening: http://233492reshet.pmd.applicaster.com/accounts/32/broadcasters/1/vod_items/3240539/e805ea5d315bc751a118/prog_index_ipad.m3u8?hdnea=exp=1440294712~acl=%2F%2A~hmac=a10bc7da98073d3c2afab52c8b6a55b3a0386f7322907f2c21af2d8d2b2de6a7|User-Agent=%25D7%25A8%25D7%25A9%25D7%25AA%2F24.8.11.46+CFNetwork%2F672.0.2&Accept-Language=en-US
23:51:51 T:796 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
......
23:51:51 T:796   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.reshet.video/?item=3240539]

ניסיון לגשת לכתובת בדפדפן מוביל לתוצאה:
An error occurred while processing your request.
Reference #199.86c9a652.1440277182.3332196

אז אני יכול רק לנחש שאולי הבעיה נובעת מהשורה הזאת:
__properties = {'pKey':'a25129723d425516a51fe2910c', 'accountId': '32', 'broadcasterId':'1', 'bundle':'com.applicaster.iReshetandroid', 'bucketId':'507fe8f13b35016f91033bfa'}
אולי החשבון הספציפי שאיתו התוסף ניגש למערכת - נחסם...

**Comment by avigdork** [comment]
באיזו מערכת הפעלה ובאיזו גירסת קודי מדובר?
דבר נוסף, אתה יכול להיכנס להגדרות ההרחבה וללחוץ על איפוס נתונים. בפעם הבאה שתפעיל את ההרחבה, יווצר לך ID חדש.

**Comment by omriamos** [comment]
אם ככה אז זה לא קשור ל ID
כי ניסיתי לאפס וזה לא עזר.. ניסיתי עכשיו שוב ליתר ביטחון, עדיין לא עזר.
Windows 7 64bit + Kodi 15.1

**Comment by avigdork** [comment]
לפעמים יש בעיות ניגון בחלק מהתוספים בגירסה 15 בוינדוס.
אני עובד עדיין עם גירסה 14.2, אני לא יודע עדיין ממה נובעת הבעיה.
דרך אגב, ביצעת שידרוג לקודי מגירסה קודמת או שהתקנת את הגירסה הזאת בפעם הראשונה על המחשב?

**Comment by omriamos** [comment]
זה היה שדרוג, אבל מגירסה 15 בטא ל-15.1
גירסה 14.2 אף פעם לא היתה מותקנת על המחשב הזה..
זה עבד ב-15 בטא, ואני חושב שזה גם עבד ב 15.1 עד לפני כמה ימים, ואז פתאום הפסיק..
הלוג לא יכול לעזור בשביל להבין מאיפה מגיעה הבעיה?

**Comment by avigdork** [comment]
זה לוג חלקי, וכמו שאמרתי לך נראה שזה הפסיק לעבוד דווקא בגלל שינויים בקודי. לא היו שינויים בתוסף בתקופה הזאת.

**Comment by omriamos** [comment]
ברור, השאלה אם לא היו שינויים באתר של רשת עצמו...
אבל אם אצלך כרגע זה עובד אז כנראה שזה באמת משהו בקודי, אני אנסה את זה על גירסה אחרת..

**Comment by noamgabay** [comment]
גם אצלי לא עובדות הרחבות מאקו רשת וערוץ 10. על אנדרואיד בקודי 15.  לא היתה מותקנת במכשיר גרסה קודמת.

**Comment by noamgabay** [comment]
אביגדור יש כיוון להתאים את התוספים לקודי 15? לחזור ל14.2 יאפס לי את הגדרות הממשק?

**Comment by avigdork** [comment]
לא יודע לגבי התאמות.
מוזר גם שלחלק זה עובד ולחלק לא.

**Comment by avigdork** [comment]
לפי בדיקה שלי, לאחר שהותקנה התקנה נקיה (מחיקה מלאה של גירסה ישנה, והתקנה חדשה של גירסה חדשה), הכל עובד.
