### ISSUE TITLE
Sdarot.tv - script failed, probably due to new cloudflare integration

### ISSUE THREAD

**Issue by nirfun** [cubicle-vdo/xbmc-israel#248]
Hi,

Sdarot.tv plugin says script failed.
Looks like sdarot introduced new cloudlfare feature to prevent DDoS attacks, so the script recieves 503 (the browser also recives 503 but then redirected by JS)

Full log:
http://pastebin.com/9uZdpYU6

**Comment by avigdork** [comment]
Try to change Domain (addon-settings) to:
http://www.sdarot.pm  (instead of http://www.sdarot.wf)

**Comment by nirfun** [comment]
Works, thanks
