### ISSUE TITLE
Unable to watch HD content

### ISSUE THREAD

**Issue by moranium** [cubicle-vdo/xbmc-israel#249]
Hi,
Since the last update, all of the content is streamed only in SD (540) , Even if you're a subscription user with credentials entered in the "settings menu".
This is a major issue, will be grateful for the fix.

Thanks!

**Comment by avigdork** [comment]
Try ver 2.1.8

**Comment by moranium** [comment]
Hi
Do you mean version 2.2.7?

**Comment by avigdork** [comment]
Yes
 :)
