### ISSUE TITLE
לא ניתן להתחבר מכתובת מחוץ לישראל לתוסף Sdarot.tv

### ISSUE THREAD

**Issue by Avishitrit** [cubicle-vdo/xbmc-israel#256]
נראה שלאחר השינויים האחרונים באתר סדרות לא ניתן להתחבר לתוסף עם כתובת מחוץ לישראל.
הגישה דרך האתר תקינה לחלוטין וגם מנהל אתר סדרות אישר שהכתובת לא חסומה בשרתים.
וידאתי את זה עם שימוש עם וי פי אן לישראל ואז הכל עובד תקין.
קובץ לוג - http://pastebin.com/N7LFvLvG

כמובן בדקתי עם משתמשים נוספים ממדינות שונות וגם אצלהם הבעיה זהה.

תודה מראש,
אבי.

**Comment by avigdork** [comment]
אני לא יודע מה אמרו לך מנהלי האתר, אבל הם הוסיפו מנגנון בדיקה שמופעל רק כשגולשים מחו"ל.
התוסף לא עודכן לעבוד עם המנגנון הזה ולכן יש הבדל בין גלישה מהארץ לגלישה מחו"ל.

**Comment by Avishitrit** [comment]
הם לא אמרו שזה אמור לעבוד, רק אמרו שאין חסימה אצלם.
תיארתי לעצמי שאכן זאת הבעיה אבל רציתי לוודא איתכם כי אין תיעוד על זה כרגע ב release notes
או בשום מקום אחר.

**Comment by avigdork** [comment]
אתה יכול לראות בגלישה לאתר מחו"ל את דף המעבר. הוא לא מופיע בגלישה מהארץ.

**Comment by Avishitrit** [comment]
לצערי אין לי יותר מידי בסיס להשוואה כי אני לא גר בישראל.
שוב תודה על האישור שזה לא אמור לעבוד בגלל השינויים האחרונים ואני אעדכן את שאר האנשים שלא הבינו לא זה הפסיק לעבוד.

**Comment by Avishitrit** [comment]
גם חשוב לציין שהדף מופיע פעם אחד כדי לקבל את ה RAY ID
באופן חד פעמי ואז הדף לא מופיע יותר אז אם אני מנסה להתחבר עם או בלי וי פי אן לישראל, הדף לא יופיע יותר עד שאני אנקה את ה cache

**Comment by shaullevi** [comment]
אני בארצות הברית שאני הולך לאתר אני רואה את דף המעבר 
![sdarot p m](https://cloud.githubusercontent.com/assets/14121140/9677075/4af47a5a-52a3-11e5-830e-51ca12350c62.JPG)
התוסף של סדרות לא עובד פה

**Comment by shaullevi** [comment]
האם אתם יכולים בבדוק את זה שזה יעבוד בקודי?

**Comment by shaullevi** [comment]
ואאו זה עבד ביומים האחרונים ושוב אני מקבל שגיאה בהרחבה 
לא עובד בכלל

**Comment by itzikg** [comment]
העיניין נפתר אפשר לנעול
