### ISSUE TITLE
Movix.Me בקשה למפתח התוסף 

### ISSUE THREAD

**Issue by itzikg** [cubicle-vdo/xbmc-israel#268]
אם אפשר בבקשה לסדר את השרתים
openload.co
videowood.tv
איכותי וזה חסר נורא HD זה שרתים שנותנים  
"ואם אפשר להוסיף קטגוריה "טלוויזיה בשידור חי
http://movix.me/tv

! תודה רבה

**Comment by itzikg** [comment]
???

**Comment by itzikg** [comment]
,שלום, ישנה בעיה באתר עם כל העיניין של הפרסומות 
ולכן נצטרך לשנות משהו קטן באתר
יהיו כנראה שני שינויים 
הפרסומת תקפוץ בכניסה לסיקור* 
יהיה לשוניות לטלוויזיה בצפייה ישירה שתחולק לקטגוריות*
אבקש לאחר השינויים שייעשו להוסיף את הקטגוריה לתוסף
הצפי לשינויים בתקווה עוד היום
!תודה

**Comment by itzikg** [comment]
???

**Comment by avigdork** [comment]
לפי מה שהבנתי התוסף נבנה עבור VOD בלבד.
התוסף משתמש ב-urlresolver למציאת הלינק לניגון.
אתה מוזמן להציע תמיכה באתרים אלו למפתח urlresolver.
