### ISSUE TITLE
kidsil nick and nick jr stopped working

### ISSUE THREAD

**Issue by OferE** [cubicle-vdo/xbmc-israel#278]
walla probably changed urls of their resources...
This is the greatest addon ever - please fix :-)

**Comment by avigdork** [comment]
Soon

**Comment by avigdork** [comment]
fixed.
try ver. 2.2.0

**Comment by OferE** [comment]
you are the best!

On Sun, Oct 18, 2015 at 10:51 PM, Avigdor <notifications@github.com> wrote:

> fixed.
> try ver. 2.2.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cubicle-vdo/xbmc-israel/issues/278#issuecomment-149041843>
> .
>



-- 
Regards,
Ofer Eliassaf

**Comment by OferE** [comment]
it was fixed. thanks! you are the best.

**Comment by OferE** [comment]
the same happens again

On Mon, Oct 19, 2015 at 5:13 AM, Ofer Eliassaf <ofer.eliassaf@gmail.com>
wrote:

> you are the best!
>
> On Sun, Oct 18, 2015 at 10:51 PM, Avigdor <notifications@github.com>
> wrote:
>
>> fixed.
>> try ver. 2.2.0
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cubicle-vdo/xbmc-israel/issues/278#issuecomment-149041843>
>> .
>>
>
>
>
> --
> Regards,
> Ofer Eliassaf
>



-- 
Regards,
Ofer Eliassaf
