### ISSUE TITLE
Playlistloader hangs

### ISSUE THREAD

**Issue by butcher211** [cubicle-vdo/xbmc-israel#286]
Hello,
sometimes Playlist-Loader isnt responding anymore after a stream doesn't works. I would like to help you with many informations as possible. So please ask me if I forgot anthing.

I saw that bug on these platforms yet:
Kodi v14 an higher installed on:
Raspberry PI
Windows x64 and x86
Apple TV 2
Amazon Fire Stick

So it must be a Bug of playlist loader I guess. There is just one playlist loaded.

**Comment by butcher211** [comment]
someone there?

**Comment by avigdork** [comment]
Please send a log file.

**Comment by butcher211** [comment]
Hello,
here is that log. I guess it doesn't happens randomly. Maybe the remote host is offline?
But as you can see in the log file, there just stand that it is loading and if I press any keys, nothing works. I just had to kill the process.

Greets!

[kodi.txt](https://github.com/cubicle-vdo/xbmc-israel/files/45640/kodi.txt)

**Comment by butcher211** [comment]
Hello,
you think, it can help, if I reproduce this error on an ARM based something like Raspberry Pi?

Greets!

**Comment by avigdork** [comment]
Hi.
The addon use the standard function 'xbmcplugin.setResolvedUrl' to play the channels.
So, if there is problems with stream sources, it's Kodi problem.
