### ISSUE TITLE
Update IsraeLIVE 4.6.2 -> Empty Channels 

### ISSUE THREAD

**Issue by Shinoby1992** [cubicle-vdo/xbmc-israel#293]
Hey! got the new update through your repo, also manually updated it in kodi
now when i start the add-on its empty and i see just the  "Favourites" Folder 

Manually updated through settings did not help or work

**Comment by avigdork** [comment]
Try re-install the addon.

**Comment by Shinoby1992** [comment]
re-installed didnt help...
deleted folder in add-on folder and install new through repo, didnt help
deleted folder in add-on folder and install through zip didnt help

**Comment by avigdork** [comment]
Try to install manually IsraeLiveResolver as well.

**Comment by Shinoby1992** [comment]
Somehow it works now, after updates
but im not sure why because it didnt worked from a backup, or reinstall but im glad that it works now.

But i saw there is another problem
whenever i activate in israellive "Enable Live TV"
i have the m3u integrated in Live TV in Kodi
now the problem.....whenever i will shutdown kodi it freezes so i have to kill the process and on Android devices i have to kill the process too...when i disable "Enable Live TV"
everything works fine again ...
would be nice to fix this, because its really annoying that i can't close kodi

**Comment by avigdork** [comment]
Thanks, I'll check it.

**Comment by Shinoby1992** [comment]
When i Activate "Enable Live TV" 
Live TV don't work without a restart of Kodi.
So i Shutdown Kodi and it does not Freeze and shutdown without problems

Then i start kodi again, now Live TV works through Israellive add-on
now i shutdown Kodi it freeze

so i think maybe it has something to do with the Localhost Server or whatever runs in the background which starts after a restart

**Comment by Shinoby1992** [comment]
Thank you for your updates, seems hanging lesser than before but still hangs for 1-2 minutes before shutdown of kodi. The german channels links seems not work anymore from one source

**Comment by Alexuu** [comment]
Dear AvigDork 

Sorry for the inconvenience I am not sure how to open a new case. First and foremost thank you for your great work with the livetv add-on. 

I have set the TV module all is well beside 2 channels that are no functioning there but are functioning very in the add-on module. 

How to fix them so they function well in the TV feature?

The 2 French channel are:
TF1 
M6 
Thank you,

Alexandre
