### ISSUE TITLE
ilten v1.3.0 - channel 10 not working

### ISSUE THREAD

**Issue by kobiavr** [cubicle-vdo/xbmc-israel#301]
ilten v1.3.0 - channel 10 not open video on kodi 15.2
i test it on openelec in pi2 
and on pc

11:27:06 1733.100220 T:1968594944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ilten/?item=3243271]

11:27:07 1733.433472 T:1968594944   ERROR: Playlist Player: skipping unplayable item: -1, path [plugin://plugin.video.ilten/?item=3243271]

11:30:03 137.017670 T:1968365568   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.ilten/)
11:30:03 137.018021 T:1968365568   DEBUG:   ParentPath = [plugin://plugin.video.ilten/]
11:30:03 137.019714 T:1968365568   DEBUG: StartScript - calling plugin ערוץ 10('plugin://plugin.video.ilten/','9','')
11:30:03 137.020432 T:1686107200  NOTICE: Thread LanguageInvoker start, auto delete: false
11:30:03 137.020615 T:1968365568   DEBUG: WaitOnScriptResult - waiting on the ערוץ 10 (id=28) plugin...
11:30:03 137.020737 T:1686107200    INFO: initializing python engine.
11:30:03 137.020844 T:1686107200   DEBUG: CPythonInvoker(28, /storage/.kodi/addons/plugin.video.ilten/ten.py): start processing
11:30:03 137.048431 T:1968365568 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
11:30:03 137.048676 T:1968365568   DEBUG: COMXImageFile::ReadFile special://skin/extras/splash.jpg GetCodingType=0x7fffffff (1400x3e8)
11:30:03 137.048798 T:1968365568  NOTICE: LoadJpeg: unable to load special://skin/extras/splash.jpg
11:30:03 137.179947 T:1686107200  NOTICE: -->Python Interpreter Initialized<--
11:30:03 137.180466 T:1686107200   DEBUG: CPythonInvoker(28, /storage/.kodi/addons/plugin.video.ilten/ten.py): the source file to load is "/storage/.kodi/addons/plugin.video.ilten/ten.py"
11:30:03 137.180908 T:1686107200   DEBUG: CPythonInvoker(28, /storage/.kodi/addons/plugin.video.ilten/ten.py): setting the Python path to /storage/.kodi/addons/plugin.video.ilten:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
11:30:03 137.181091 T:1686107200   DEBUG: CPythonInvoker(28, /storage/.kodi/addons/plugin.video.ilten/ten.py): entering source directory /storage/.kodi/addons/plugin.video.ilten
11:30:03 137.181488 T:1686107200   DEBUG: CPythonInvoker(28, /storage/.kodi/addons/plugin.video.ilten/ten.py): instantiating addon using automatically obtained id of "plugin.video.ilten" dependent on version 2.1.0 of the xbmc.python api
11:30:03 137.496780 T:1686107200   DEBUG: ***** deviceId --> d12389298273474
11:30:03 137.497101 T:1686107200   DEBUG: ***** UUID from settings --> 56131d0269702d697c069dbe, auth token from settings --> e1e2d8d12a58
11:30:03 137.497238 T:1686107200   DEBUG: ***** final UUID --> 56131d0269702d697c069dbe, final auth token --> e1e2d8d12a58
11:30:04 138.456009 T:1686107200   DEBUG: ***** accountURL --> http://admin.applicaster.com/v12/accounts/69.json?api[bundle]=com.applicaster.il.tenandroid&api[bver]=1.9.3&api[device_model]=Nexus+7&api[os_type]=android&api[os_version]=17&api[sig]=b0d77520a02b5009ed0bb2a48d7d4ba8&api[timestamp]=1447407003&api[token]=d12389298273474&api[uuid]=56131d0269702d697c069dbe&api[ver]=1.2
11:30:04 138.458557 T:1686107200   DEBUG: ***** Programs category id --> 1441
11:30:04 138.459641 T:1686107200   DEBUG: ***** CategoryURL --> http://admin.applicaster.com/v12/accounts/69/broadcasters/67/categories/1441.json?api[bundle]=com.applicaster.il.tenandroid&api[bver]=1.9.3&api[device_model]=Nexus+7&api[os_type]=android&api[os_version]=17&api[sig]=c755064bf610efecc7b82e8502a134af&api[timestamp]=1447407004&api[token]=d12389298273474&api[uuid]=56131d0269702d697c069dbe&api[ver]=1.2
11:30:04 138.663803 T:1686107200   DEBUG: ***** category --> 1945
11:30:04 138.665970 T:1686107200   DEBUG: ***** category --> 1940
11:30:04 138.666489 T:1686107200   DEBUG: ***** category --> 1975
11:30:04 138.667023 T:1686107200   DEBUG: ***** category --> 1941
11:30:04 138.667419 T:1686107200   DEBUG: ***** category --> 1942
11:30:04 138.668228 T:1686107200   DEBUG: ***** Retrieving item_list with ID 121
11:30:05 138.989914 T:1686107200   DEBUG: ***** category --> 3891
11:30:05 138.990768 T:1686107200   DEBUG: ***** category --> 3764
11:30:05 138.991257 T:1686107200   DEBUG: ***** Retrieving item_list with ID 82
11:30:05 139.152252 T:1686107200   DEBUG: ***** Retrieving item_list with ID 97
11:30:05 139.323486 T:1686107200   DEBUG: ***** Retrieving item_list with ID 98
11:30:05 139.642242 T:1968365568   DEBUG: WaitOnScriptResult- plugin returned successfully
11:30:05 139.642807 T:1686107200    INFO: CPythonInvoker(28, /storage/.kodi/addons/plugin.video.ilten/ten.py): script successfully run
11:30:05 139.658585 T:1591735360  NOTICE: Thread BackgroundLoader start, auto delete: false
11:30:05 139.706360 T:1591735360   DEBUG: Thread BackgroundLoader 1591735360 terminating

**Comment by avigdork** [comment]
Hi,
Could you attach a link for a full log?

**Comment by kobiavr** [comment]
hi
http://goo.gl/ZEZpnm
thank you

**Comment by avigdork** [comment]
Is it solved for you in new versions?

**Comment by kobiavr** [comment]
Now everything works great
Thank you

2016-01-05 14:45 GMT+01:00 Avigdor <notifications@github.com>:

**Comment by avigdork** [comment]
:+1:
