### ISSUE TITLE
Mako - Add option to enter the paid user name and password

### ISSUE THREAD

**Issue by kyaron** [cubicle-vdo/xbmc-israel#312]
Hi, 
How about adding an option under settings to add the user name and password if it was paid?
Thanks

**Comment by doclucas** [comment]
Yes, this is a great idea
+1

**Comment by avigdork** [comment]
We'll need username & password to check it.

**Comment by doclucas** [comment]
Please provide email address to send the user/pass to....

**Comment by doclucas** [comment]
@avigdork we can't post our username/password here, we need your email address to send you the details...
Thanks

**Comment by kyaron** [comment]
I can test it for you.

**Comment by avigdork** [comment]
Hi, I need the user/pass just for one time, to see the traffic to/from Mako server.
you can send the details to:
send.again@outlook.com

**Comment by doclucas** [comment]
Hi, I am sending to you my Mako login details. Hope this will help developing a solution for paid users.

Thanks
