### ISSUE TITLE
adding request header to Mako

### ISSUE THREAD

**Issue by doclucas** [cubicle-vdo/xbmc-israel#322]
Thanks for your wonderful scripts! :)

As you may know, Mako is blocking non-Israeli IPs from getting most content, such as "The Big Brother" etc. which is also free (non-paid).
There is a way to workaround this problem by sending an Israeli IP header using X-FORWARDED-FOR header, as explained here: https://www.reddit.com/r/Israel/comments/361jri/%D7%9C%D7%9E%D7%91%D7%99%D7%A0%D7%99%D7%9D_%D7%91%D7%9E%D7%97%D7%A9%D7%91%D7%99%D7%9D_%D7%99%D7%A9_%D7%93%D7%A8%D7%9A_%D7%9C%D7%A2%D7%A7%D7%95%D7%A3_%D7%90%D7%AA_%D7%94%D7%9E%D7%A2%D7%A8%D7%9B%D7%AA_%D7%A9%D7%9C_%D7%9E%D7%90%D7%A7%D7%95/

This works very well in the browser when browsing their website.

I have edited the file mako.py from makoTV.video addon
_acceptHeader = '&Accept-Language=en-US&X-Forwarded-For=192.118.82.223'

It now works fine for most of the big brother videos, although fails for some files like season 7 episode 4 (getting 403 error in the kodi.log) while this episode plays fine on mako website when I am adding the fake IP via the header.

I also tried editing the makoTV (web) addon by changing default.py as below (changes in bold):
    def OpenURL(url, headers={}, user_data={}, retries=3):
    	if user_data:
    		user_data = urllib.urlencode(user_data)
    		req = urllib2.Request(url, user_data)
    		**req.add_header('X-Forwarded-For','192.118.82.223')**
    	else:
    		req = urllib2.Request(url)
    	UA = "Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3"
    	req.add_header('User-Agent', UA)
    	**req.add_header('X-Forwarded-For',"192.118.82.223")**
    	for k, v in headers.items():
    		req.add_header(k, v)

Unfortunately, this method doesn't work, but I have no idea why.

Can you please add a way to send the X-FORWARDED-FOR header correctly to all servers (mako, akamai etc.) via these scripts and add the IP configuration option in the GUIs settings?
I am sure this will help many Israelis who stay abroad and use your scripts. :)

**Comment by avigdork** [comment]
Try this beta ver. 
Change the forwarded ip in addon settings.

[plugin.video.MakoTV-1.1.2~beta1.zip](https://github.com/cubicle-vdo/xbmc-israel/files/78402/plugin.video.MakoTV-1.1.2.beta1.zip)

**Comment by doclucas** [comment]
Works perfectly, Thanks!!! :+1: 
:-)

**Comment by avigdork** [comment]
Grate.

**Comment by avigdork** [comment]
@doclucas 
What is the IP '192.118.82.223' ?
Is it matter witch Israeli IP I choose?

**Comment by doclucas** [comment]
@avigdork 
It's just a random Israeli IP and does not matter what Israeli IP you set. You can read more in the reddit.com link I posted above

**Comment by avigdork** [comment]
:+1:
