### ISSUE TITLE
OpenElec 6

### ISSUE THREAD

**Issue by aladin2000** [cubicle-vdo/xbmc-israel#330]
High

I tried to include the code 
 xbmc-israel/repo/plugin.video.playlistLoader/plugin.video.playlistLoader-1.0.9.zip
 as an extension from zip to OpenElec Kodi
The result is "missing dependencies" to be able to compile 
Would you like to help me in finding a solution. 
MY platform:  Raspberry B, Berry boot  , Openelec 6.0 
thanks by advance

**Comment by avigdork** [comment]
Install the repo first

**Comment by aladin2000** [comment]
thanks a lot I will try it
