### ISSUE TITLE
Israel Live cant open any channel

### ISSUE THREAD

**Issue by mejdan95** [cubicle-vdo/xbmc-israel#352]
Hey guys, Israel ad-don is working fine, it loads the channels but cant play any. It works fine if I open channels directly from ad-don, but it want open any with simple client PVR. I uninstalled it, deleted data, disabled PVR Simple Client, installed it again, enabled TV in Kodi and it looks like everything is working fine, it loads channels and it makes guide, it's showing the signal below each channel but it cant play any channels. Please help. 
Thanks.

**Comment by avigdork** [comment]
Hi.
Can you send more details about: Kodi version, platform, skin.
Please send a link to log file too.
http://kodi.wiki/view/Log_file/Advanced#Easy_ways_to_get_and_post_the_log_file

**Comment by mejdan95** [comment]
Hi, thank you for responding. I have Kodi 15.2 with "the beast" installed. I have it on my fire tv stick so I'm not sure how to send you a link. I forgot to mention that Israel is one of my favorites, and I love it because it does everything on it on, picture quality is simply great, and never freeze's. Install the addon, enable TV and PVR simple client and it downloads the channels and guide on it own. I never, ever had any single issue with it till yesterday. For some reason it wouldn't play any channels. Last night I removed it two times, disabled TV and PVR, cleared data few times, and installed it again. It plays some of the channels now but not all of them. I mainly use English channels, Entertainment and movies since I don't understand other languages. I'm able to watch some of the channels today but not all of them. Hope this helps.

**Comment by mejdan95** [comment]
Israel is working at all now. I installed Kodi 16, but now it want load at all. Get the message that is unable to log settings.

**Comment by avigdork** [comment]
Try vesion 4.7.5
