### ISSUE TITLE
Invalid base64 padding

### ISSUE THREAD

**Issue by atyachin** [cubicle-vdo/xbmc-israel#361]
Addon fails to load the remote config file on Sony Bravia x850c Android TV.
Log file: http://xbmclogs.com/paakufqpc
(Lines 195-212)

**Comment by atyachin** [comment]
Addon fails to load the remote config file on Sony Bravia x850c Androx850c.
Log file: http://xbmclogs.com/paakufqpc

**Comment by avigdork** [comment]
Hi. 
Sorry, I forgot to reply. 
Please try now on version 4.8.0.

**Comment by atyachin** [comment]
thanks! all good now.
