### ISSUE TITLE
PVR IPTV Simple Client

### ISSUE THREAD

**Issue by wexi** [cubicle-vdo/xbmc-israel#375]
Shalom!

Using Ubuntu 16.10 Linux with 
Kodi 16.1 Git C372C53
PVR... V1.12.12
IsraelLive 4.8.4

The PVR does not auto launch (it is enabled). Any idea how to fix?

A lazy person question: Is it possible to have Kodi use the xbmc-israel github repo directly?. 

Also, some key streams don't work: Radio: Reshet Bet, Galei Zahal, TV: Channel 1, ...  
I guess it's Linux unfriendly Adobe Flash to blame. Could this be overcome by auto launch of Chrome sub-windows?

Toda Raba, Enoch.

**Comment by avigdork** [comment]
Hi.
Probably, there was a problem to update IPTV Simple settings.
Open PVR IPTV Simple Client settings and check if the M3U Play List Path is set to your profile folder.
If not, change one of the settings (change the Location method for example) and click on OK button, then open IsraeLIVE settings, go to LiveTV tab and click on "Refresh all LiveTV required resources"

![screenshot029](https://cloud.githubusercontent.com/assets/3647525/15631586/dd37370a-2579-11e6-9ecb-0e6336ab77f2.png)
