### ISSUE TITLE
French Channel Not functioning in the PVR 

### ISSUE THREAD

**Issue by Alexuu** [cubicle-vdo/xbmc-israel#382]
Dear AvigDork

First and foremost thank you for your great work with the livetv add-on. Stable, great quality and very comprehensive channels collection.

I have set the TV pvr module all is well beside 2 channels that are no functioning there but are functioning very well in the add-on module it self. 

So how can I fix them so they function well in the TV feature?

The 2 channels are in the French section :
TF1 
M6 

Thank you,

**Comment by avigdork** [comment]
Hi. thanks.
Sorry, but those channels can played only via the addon right now.

**Comment by Alexuu** [comment]
Hi, Thank you for your reply. 
Those are the two that can only be played from the add-on? There is nothing to be done to be able to play them from the TV pvr?
Thank you 

Get Outlook for iOS




On Sun, Jul 10, 2016 at 4:10 PM +0400, "Avigdor" <notifications@github.com> wrote:












Hi. thanks.

Sorry, but those channels can played only via the addon right now.

**Comment by avigdork** [comment]
Not for now.
I'll check if I can do something about it/

**Comment by Alexuu** [comment]
Thank you very much for your kind support and  time. Very appreciated.
Alex 

Get Outlook for iOS




On Sun, Jul 10, 2016 at 4:15 PM +0400, "Avigdor" <notifications@github.com> wrote:












Not for now.

I'll check if I can do something about it/

**Comment by avigdork** [comment]
I found a way to get it work. 
I'll make some tests and upload a new version.

**Comment by Alexuu** [comment]
Brilliant thank you highly appreciated.
Quick one, The font in the text does seems to support character. Is it something that I cab do on my side to be able to read the description?
Alexandre 

Get Outlook for iOS




On Sun, Jul 10, 2016 at 6:30 PM +0400, "Avigdor" <notifications@github.com> wrote:












I found a way to get it work. 

I'll make some tests and upload a new version.

**Comment by avigdork** [comment]
Try to change the font at System - Settings -  Appearance to Arial based.

**Comment by Alexuu** [comment]
Beautiful, done.FYI - Only 3 channels remain in Hebrew. France 2 TV5 Arte
With thanks and regards 
Alexandre 

Get Outlook for iOS




On Sun, Jul 10, 2016 at 9:59 PM +0400, "Avigdor" <notifications@github.com> wrote:












Try to change the font at System - Settings -  Appearance to Arial based.

**Comment by Alexuu** [comment]
Found a Facebook page mentioning vstream 2, what's new on there?
https://m.facebook.com/permalink.php?story_fbid=1511666635795581&id=1511659055796339

Get Outlook for iOS




On Sun, Jul 10, 2016 at 10:43 PM +0400, "Alexandre Usseglio" <michelleusseglio@gmail.com> wrote:










Beautiful, done.FYI - Only 3 channels remain in Hebrew. France 2 TV5 Arte
With thanks and regards 
Alexandre 

Get Outlook for iOS




On Sun, Jul 10, 2016 at 9:59 PM +0400, "Avigdor" <notifications@github.com> wrote:












Try to change the font at System - Settings -  Appearance to Arial based.

**Comment by Alexuu** [comment]
Sorry wrong ignore.

Get Outlook for iOS




On Sun, Jul 10, 2016 at 11:13 PM +0400, "Alexandre Usseglio" <michelleusseglio@gmail.com> wrote:










Found a Facebook page mentioning vstream 2, what's new on there?
https://m.facebook.com/permalink.php?story_fbid=1511666635795581&id=1511659055796339

Get Outlook for iOS




On Sun, Jul 10, 2016 at 10:43 PM +0400, "Alexandre Usseglio" <michelleusseglio@gmail.com> wrote:










Beautiful, done.FYI - Only 3 channels remain in Hebrew. France 2 TV5 Arte
With thanks and regards 
Alexandre 

Get Outlook for iOS




On Sun, Jul 10, 2016 at 9:59 PM +0400, "Avigdor" <notifications@github.com> wrote:












Try to change the font at System - Settings -  Appearance to Arial based.

**Comment by avigdork** [comment]
Hi. 
Try version 4.8.7
Don't forget to restart Kodi after the update.

**Comment by avigdork** [comment]
I see that channel M6 can't play on LiveTV, there is error from Livestreamer:
"Need pyCrypto installed to decrypt this stream" 
(The player of Kodi that used in the addon can do it.)

**Comment by Alexuu** [comment]
Hi,
Can't find the version you mentioned. 

Get Outlook for iOS




On Mon, Jul 11, 2016 at 8:49 PM +0400, "Avigdor" <notifications@github.com> wrote:












Hi. 

Try version 4.8.7

Don't forget to restart Kodi after the update.

**Comment by Alexuu** [comment]
Hi, Sorry wrong add-on....
I did upgraded to the version listed below, however, TF1 is active but not info and M6 not yet indeed. Will try to install the program you mentioned. 

Thank you for your kind help. 



Get Outlook for iOS

		_____________________________

**Comment by avigdork** [comment]
Hi, there is new version 4.8.8.
I added an option in addon settings at LiveTV tab to choose a player for dynamic channels. 
Try to choose Kodi-player instead of Livestreamer, restart Kodi, then you could play M6 from LiveTV.

**Comment by Alexuu** [comment]
Amazing... I will try that asap. 
Thanks again for your kind effort.
Alexandre 

Get Outlook for iOS




On Tue, Jul 12, 2016 at 7:46 PM +0400, "Avigdor" <notifications@github.com> wrote:












Hi, there is new version 4.8.8.

I added an option in addon settings at LiveTV tab to choose a player for dynamic channels. 

Try to choose Kodi-player instead of Livestreamer, restart Kodi, then you could play M6 from LiveTV.
