### ISSUE TITLE
Mako - Add option to enter the paid user name and password (follow-up)

### ISSUE THREAD

**Issue by doclucas** [cubicle-vdo/xbmc-israel#388]
Hi,

I am creating this new issue since the previous one has been closed.
I sent you my username and password to the email address you provided.
They will expire soon.
Hopefully we can get the paid content accessible via this addon soon :)

Thank you :)

**Comment by avigdork** [comment]
Thanks. 
We'll check how to make it work.

**Comment by avigdork** [comment]
@doclucas 
I sent you an email, please try the attached file.

**Comment by avigdork** [comment]
Added to version 1.1.7

**Comment by doclucas** [comment]
Tested and working great! Thank you so much! :) :+1:

**Comment by avigdork** [comment]
Great. Have fun.
