### ISSUE TITLE
Error restart XBMC/Kodi

### ISSUE THREAD

**Issue by sergienko4** [cubicle-vdo/xbmc-israel#392]
Hi, I started to receive this error, I tried to reinstall kodi and add-on but same issue.
I'm using Ubuntu 16.04
any idea ?

thx

**Comment by avigdork** [comment]
Hi.
Try to delete addon folder from userdata folder.

**Comment by sergienko4** [comment]
that is doesn't help. i installed a new version of KODI 17.0 now i can install the add-on.

**Comment by sergienko4** [comment]
do you have a solution for me ?

**Comment by avigdork** [comment]
Hi. 
Can you please attach a log file?

**Comment by sergienko4** [comment]
You

 can download from here  or by this link 
http://expirebox.com/download/7c98558fe988e6bf58dcbb3a8f9f1c42.html
[Uploading kodi.log.zip…]()

**Comment by sergienko4** [comment]
do you have a solution for me ?

**Comment by avigdork** [comment]
Do you try it on kodi 16.1?
I can't see what exactly the problem. 
When do you get the error? 
Maybe one of the dependencies not installed?

**Comment by sergienko4** [comment]
How can i install 16.1 on Ubuntu ?
That happened when I open the Israel live add-on or the kodi is ready to use.

**Comment by avigdork** [comment]
I don't know, I never try it.
Check here: [http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux](url)
Did you enable debug log before you create this log file?

**Comment by sergienko4** [comment]
Yes I enabled .
I'll try to check on this site . I can send you a new log if you want

**Comment by avigdork** [comment]
OK, send a new log and attach a print-screen with the error.

**Comment by sergienko4** [comment]
You can find it here
https://www.dropbox.com/s/42mdmjybndw3pbw/kodi.log.zip?dl=0
 thx

 *אם אתה באמת רוצה אתה תמצא דרך, אם לא אתה תמצא תרוץ*
*P*    *שומרים על איכות הסביבה **נא להימנע מהדפסת מייל זה שלא לצורך*
*.          * *P **Please consider the environment before printing this
email or any attachments.*

**Comment by avigdork** [comment]
Hi. Try to unzip both IsraeLive and IsraeLiveResolver into addons folder. 
After that restart Kodi, go to IsraeLive settings, press advanced settings and Mark unverify ssl. 

https://github.com/cubicle-vdo/xbmc-israel/blob/master/repo/script.module.israeliveresolver/script.module.israeliveresolver-0.2.9.zip

https://github.com/cubicle-vdo/xbmc-israel/blob/master/repo/plugin.video.israelive/plugin.video.israelive-4.9.2.zip

**Comment by sergienko4** [comment]
Hi, now change I have the some problem, always
"please restart the kodi"
My dropbox link for shortcut and the log
https://www.dropbox.com/s/kj3w1z8xl93t7f2/KodiError.zip?dl=0


 *אם אתה באמת רוצה אתה תמצא דרך, אם לא אתה תמצא תרוץ*
*P*    *שומרים על איכות הסביבה **נא להימנע מהדפסת מייל זה שלא לצורך*
*.          * *P **Please consider the environment before printing this
email or any attachments.*

**Comment by avigdork** [comment]
You can try install IsraeLiveResolver version 0.3.0

**Comment by sergienko4** [comment]
Is that a new version ?  Can I download it from the Israel repo or other
source ?

On 21 Aug 2016 3:43 p.m., "Avigdor" <notifications@github.com> wrote:

You can try install IsraeLiveResolver version 0.3.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cubicle-vdo/xbmc-israel/issues/392#issuecomment-241255286>,
or mute the thread

**Comment by avigdork** [comment]
You can download it from this repo (XBMC Israeli streaming sites repo.)
or directly from:
https://github.com/cubicle-vdo/xbmc-israel/blob/master/repo/script.module.israeliveresolver/script.module.israeliveresolver-0.3.0.zip

**Comment by sergienko4** [comment]
Finally it worked , thank you for the help.


 *אם אתה באמת רוצה אתה תמצא דרך, אם לא אתה תמצא תרוץ*
*P*    *שומרים על איכות הסביבה **נא להימנע מהדפסת מייל זה שלא לצורך*
*.          * *P **Please consider the environment before printing this
email or any attachments.*

**Comment by avigdork** [comment]
:-)
