### ISSUE TITLE
channel 20 live stream

### ISSUE THREAD

**Issue by dude4** [cubicle-vdo/xbmc-israel#395]
hi
url should be changed, as its not working anymore.
live stream can be fetched from here: http://live.ch20-cdnwiz.com/ch20-abr/ch20-abr/playlist.m3u8

Thanks!

**Comment by avigdork** [comment]
Hi. 
This url already updated yesterday.. 
Your list isn't updated. Try to update channels list from addon settings.

**Comment by dude4** [comment]
cool, thanks!

btw, where are the channel list being fetched from? i couldn't find it in the code..
