### ISSUE TITLE
Israelive - Please restart kodi all the time

### ISSUE THREAD

**Issue by GreenBlast** [cubicle-vdo/xbmc-israel#396]
Hi, there is an issue (right now on raspberry pi 3, raspbian) that the popup message: "Please restart xbmc/kodi" keeps showing up. And the addon is not getting loaded.

I traced the problem to the pyopenssl.py file at the israelresolver. The attribute PROTOCOL_SSLv3 is not exist the ssl library that sits on the device apparently. Quick fix was to comment this specific line.

`# Map from urllib3 to PyOpenSSL compatible parameter-values.`
`_openssl_versions = {`
`    ssl.PROTOCOL_SSLv23: OpenSSL.SSL.SSLv23_METHOD,`
`    #ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,`
`    ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,`
`}`

**Comment by avigdork** [comment]
Thanks, I fixed it in version 0.3.0
