### ISSUE TITLE
filmon links down

### ISSUE THREAD

**Issue by totaltec2014** [cubicle-vdo/xbmc-israel#404]
as of 02 / 11 i guess the resolver needs a tweak as all filmon links are down at present thank you

**Comment by totaltec2014** [comment]
12:41:42 T:12076  NOTICE: Creating InputStream
12:41:42 T:12076   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
12:41:42 T:12076   ERROR: CCurlFile::Open failed with code 403 for http://live-1273.fra.edge.filmon.com/live/3227.high.stream/playlist.m3u8?id=0ad5aac39bb13fbe8ddc26284f6156fff0bf7f8c988a3a4ba7013731010ffeacceac90523a1b222820deba2bc645c953f933d0fca27bcf7e494b469f583bc92898acd1940329ad1432b659881b63f6e762f76ddb74104184976004b3990dde71bebc35eddd612cc0af42318efea24af24b5c3577d9a2483d4997d4579edc086137744772be699d9d91a20d6ee0086753bb6689a6d0098b6c
12:41:42 T:12076   ERROR: XFILE::CFileCache::Open - failed to open source <http://live-1273.fra.edge.filmon.com/live/3227.high.stream/playlist.m3u8?id=0ad5aac39bb13fbe8ddc26284f6156fff0bf7f8c988a3a4ba7013731010ffeacceac90523a1b222820deba2bc645c953f933d0fca27bcf7e494b469f583bc92898acd1940329ad1432b659881b63f6e762f76ddb74104184976004b3990dde71bebc35eddd612cc0af42318efea24af24b5c3577d9a2483d4997d4579edc086137744772be699d9d91a20d6ee0086753bb6689a6d0098b6c>

**Comment by kostaboxon** [comment]
Confirmed, 
Same here.

**Comment by avigdork** [comment]
Hi. 
I'll check it this week. 
Meanwhile you can try change filmon protocol from hls to rtmp (addon settings)

**Comment by kostaboxon** [comment]
Changed filmon protocol to rtmp. 
Worked. No idea what the issue is but i will monitor and go to defaults when i hear.

**Comment by totaltec2014** [comment]
Both rtmp and HLS now down also seems that time of the year again for filmon to make changes avigdork many thanks for your time ive loved this addon and tbf filmon streams for years :) hopefully it can be fixed

**Comment by avigdork** [comment]
I updated the resolver.
It's playing now only the low quality. (It's better than nothing..)

**Comment by JoeFatNC** [comment]
Still not able to stream. Any updates?

**Comment by avigdork** [comment]
@JoeFatNC, make sure the version of IsraeLiveResolver addon is 0.3.1.
Try to watch from IsraeLIVE addon. 
You need to restart Kodi after IsraeLiveResolver update if you want the changes affect the LiveTV too.

**Comment by kostaboxon** [comment]
IsraeLiveResolver addon is 0.3.1.
It is BBC1 which opens and then kick out after 10 seconds. Ireland,Scotland,Wales BBC all fail.
All itv channels fail. I will wait for Update. Israel live addon used.Entertainment Section.

**Comment by avigdork** [comment]
@kostaboxon, did you try hls and rtmp? 
You can choose the protocol in addon settings.

**Comment by JoeFatNC** [comment]
Running IsraeLiveResolver version 0.3.1 and tried watching from IsraeLive. After selecting stream (any channel) receive "Playback failed" and "cannot resolve stream for channel". Tried reinstalling with Kodi restart and still get same results? Not sure what else to try.

**Comment by avigdork** [comment]
Can you please attach a log?

**Comment by kostaboxon** [comment]
@kostaboxon, did you try hls and rtmp? 
You can choose the protocol in addon settings.
Tried both with identical results. No Difference hls or rtmp for me.
Same results as my previous comment
If logs are required let me know as I'm not with the box at the moment.

**Comment by JoeFatNC** [comment]
I'm running on fire stick and have "easy log viewer" but no sure how to forward the error log. Will have to do some more research and become more than novice user.

**Comment by kostaboxon** [comment]
It came good today.
No idea what happened. Still same Israel Live Resolver.
Tried HLS Protocol and that works as well. I've left it HLS Default.

**Comment by avigdork** [comment]
Yes, I changed something yesterday. 
There is no RTMP now (No matter what you choose, it will play HLS), I'll update addon settings in next ver.

**Comment by JoeFatNC** [comment]
Yes and thanks.... staring working for me as well.

**Comment by avigdork** [comment]
:+1:

**Comment by totaltec2014** [comment]
hi guys im stuggling to get any links to resolve or play in israel live anyone else having issues?  checked filmon derivatives and all ok this is on pc and libreelec

**Comment by yaron08** [comment]
Yes, I can't see any channel from Israel Live

**Comment by kostaboxon** [comment]
I have been watching the entertainment section BBC1 & BBC2 
Also watching News section all working as normal.
You might want to disclose what version you are on.

**Comment by avigdork** [comment]
Please make sure that IsraeLIVE version is 4.9.8
