### ISSUE TITLE
IsraeLIVE 4.9.7 Empty channel lists

### ISSUE THREAD

**Issue by aaroncox31** [cubicle-vdo/xbmc-israel#410]
After updating to 4.9.7, if "show only selected categories" is enabled all the lists turn empty.
Disabling this feature and removing all marked categories brings the channels back.

**Comment by avigdork** [comment]
Thanks. 
I'll check it.

**Comment by avigdork** [comment]
@aaroncox31 
I's working for me.
Did you try to reopen the addon after you changed to show/hide selected categories?
You can try to remove the categories and select them again.

**Comment by aaroncox31** [comment]
> Did you try to reopen the addon after you changed to show/hide selected categories?
Yes, I exited kodi and reopened it.

> You can try to remove the categories and select them again.
I did, no effect.

I would like to mention that this happned on 3 diffrent kodi installations. All 16.1, 2 on android and another on windows 10.

**Comment by avigdork** [comment]
Hi. 
Can you please send me the selectedCategories.txt file from your profile folder (in lists folder that indide addon folder)?

**Comment by aaroncox31** [comment]
There is no selectedCategories.txt file. 
I have a selectedCategories.list file in the lists folder:
https://dl.dropboxusercontent.com/u/22748480/selectedCategories.list
a categories.list file in the lists folder:
https://dl.dropboxusercontent.com/u/22748480/categories.list
and a israelive.list file in the addon folder:
https://dl.dropboxusercontent.com/u/22748480/israelive.list

**Comment by avigdork** [comment]
Hi, 
Just now I realized what you wrote.
I thought you cannot see the selected categories themself..
Now I see that if you enter to a category the list of channels is empty.
I'll fix it in next version.

Thanks, again

**Comment by avigdork** [comment]
@aaroncox31 
Please check version 4.9.8

**Comment by aaroncox31** [comment]
@avigdork I did, looks like it's working

**Comment by avigdork** [comment]
:)
