### ISSUE TITLE
Bug in the latest version

### ISSUE THREAD

**Issue by krok55** [cubicle-vdo/xbmc-israel#412]
Hi,

I think I found a bug:

The log says: "need more than 2 values to unpack"
I tried to look in the code and found that in line 147 (default.py):
`channelName, programmeName, description = GetPlayingDetails(urllib.unquote_plus(name), categoryID)`
Three output parameters are expected.

But inside GetPlayingDetails there is a case where (lines 162,163):
`	if not useEPG:
		return programmeName, programmeName`
only two retrieved...

**Comment by avigdork** [comment]
@krok55 
You're right. 
I missed it and will fix it next version.
You can fix it by enable the EPG in addon settings, or by change the line 163 to:
return programmeName, programmeName, None

**Comment by avigdork** [comment]
Hi.
Please check ver 4.9.9
