### ISSUE TITLE
libre elec openelec no channels play

### ISSUE THREAD

**Issue by totaltec2014** [cubicle-vdo/xbmc-israel#413]
got it working on my pc fine but on libreelec no channels stream 

13:10:22 T:3041337920   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.israelive/?mode=10&iconimage=http%3A%2F%2Fstatic.filmon.com%2Fcouch%2Fchannels%2F11%2Fextra_big_logo.png&channelid=10126&categoryid=10087]

**Comment by avigdork** [comment]
Hi.
Can you check it again?
I added User-Agent, it help sometimes..

**Comment by totaltec2014** [comment]
tried force agent in urls resolver settings set defaults in israel live but same no channels play using openele or librelelec

12:27:16 T:4115030592   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.israelive/?mode=10&iconimage=http%3A%2F%2Fstatic.filmon.com%2Fcouch%2Fchannels%2F361%2Fextra_big_logo.png&channelid=10116&categoryid=10087]
12:27:16 T:4047725472   ERROR: CecLogMessage - Write: write failed !
12:27:18 T:308278176   ERROR: Previous line repeats 3 times.
12:27:18 T:308278176   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/v/t1.0-1/p160x160/1013710_199451146894399_2142745926_n.jpg?oh=8326aec6656419e6ed4435fc63ab1baa&oe=56450B51&__gda__=1447643195_e51fbe3f3948b04f2f072bc4b329477d
12:27:19 T:4047725472   ERROR: CecLogMessage - Write: write failed !
12:27:21 T:3904893856   ERROR: Previous line repeats 2 times.
12:27:21 T:3904893856 WARNING: need more than 2 values to unpack
12:27:21 T:4047725472   ERROR: CecLogMessage - Write: write failed !
12:27:21 T:4115030592   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.israelive/?mode=10&iconimage=http%3A%2F%2Fstatic.filmon.com%2Fcouch%2Fchannels%2F361%2Fextra_big_logo.png&channelid=10116&categoryid=10087]
12:27:22 T:4047725472   ERROR: CecLogMessage - Write: write failed !

**Comment by avigdork** [comment]
Did you disabled the EPG in addon settings?
I have an open bug that will be fix on next version.

**Comment by totaltec2014** [comment]
thank you i did try everything i could think of tbf but same error each time on libreelec . and many thanks for taking time to look i look fwd to the update to try

**Comment by totaltec2014** [comment]
okay did some more digging installed 4.9.6 and channels load ok

**Comment by totaltec2014** [comment]
not sure if me going on helps but 4.9.8 resolver with 4.9.5 or 4.9.6 addon works fine guys thanks

**Comment by avigdork** [comment]
Hi.
Can you try ver 4.9.9?

**Comment by totaltec2014** [comment]
you guys are great working perfect on libreelec now on 4.9.9

**Comment by avigdork** [comment]
:+1:
