### ISSUE TITLE
Playing ACESTREAM playlists with plexus

### ISSUE THREAD

**Issue by jimmycr** [cubicle-vdo/xbmc-israel#417]
Avigdor, I managed how to play ACESTREAM playlists (.M3U) with your plugin and "Plexus" plugin.

Your code of default.py file (around line 136):

> def PlayUrl(name, url, iconimage=None):
        print '--- Playing "{0}". {1}'.format(name, url)
  	listitem = xbmcgui.ListItem(path=url, thumbnailImage=iconimage)
	listitem.setInfo(type="Video", infoLabels={ "Title": name })
	xbmcplugin.setResolvedUrl(int(sys.argv[1]), True, listitem)

New code of default.py file (around line 136):

> def PlayUrl(name, url, iconimage=None):
	print '--- Playing "{0}". {1}'.format(name, url)
	if "acestream://" in url: 
		listitem = xbmcgui.ListItem(path="plugin://program.plexus/?mode=1&url="+url+"&name="+name, thumbnailImage=iconimage)
	else:
        	listitem = xbmcgui.ListItem(path=url, thumbnailImage=iconimage)
	listitem.setInfo(type="Video", infoLabels={ "Title": name })
	xbmcplugin.setResolvedUrl(int(sys.argv[1]), True, listitem)

Is it possible to add dialog or something to force plugin to play ACESTREAM using user-defined plugin? (so we can user-friendly add "plugin://program.plexus/?mode=1&url=" for example)
Thanks!

jimmy

**Comment by avigdork** [comment]
Hi, Jimmy
You already can play links to another plugins, for example:
plugin://program.plexus/?mode=1&url=acestream://9dfc3790aa36bd3cfce54bc0d9d42a1062556043&name=Video

**Comment by jimmycr** [comment]
How then? For example - Sports playlist can be found here:
http://super-pomoyka.us.to/trash/ttv-list/ttv.sport.player.m3u
If I open it with Playlist Loader it will not send it to Plexus, will it?
Thanks for help :)

**Comment by avigdork** [comment]
@jimmycr 
OK, I'll add rout acestream links to plexus.

**Comment by jimmycr** [comment]
will try...If it will work, you`re the best!

**Comment by jimmycr** [comment]
working as expected - great job! Thank you!
