### ISSUE TITLE
Reshet stopped showing content

### ISSUE THREAD

**Issue by hllhll** [cubicle-vdo/xbmc-israel#431]
Hi,

It seems like the reshet plugin stopped showing content in a specific program.
URL For the specific show seems to contain no episides (hence Kodi shows no episode).
Tried to put proxy on the android app, seems like no request goes out when a specific show is selected... I'd fix it if someone could give a lead

**Comment by hllhll** [comment]
It seems that the cause is that the API returns no episodes for newer shows. [Here](https://github.com/hllhll/xbmc-israel) is a little work to scrape off the url to the episodes from the web pages. Still initial and buggy but kindda works, but link retrived is very low quality.

**Comment by avigdork** [comment]
Hi.
You can send PR when you have a fix.
Thanks

**Comment by hllhll** [comment]
I Don't think it's good enougth for a PR yet, but[ I Just fixed some stuff ](https://github.com/hllhll/xbmc-israel)and it works sortta ok

**Comment by avigdork** [comment]
@hllhll 
Hi, your changes is now in version 1.3.4
