### ISSUE TITLE
French Guide — Hebrew 

### ISSUE THREAD

**Issue by Alexuu** [cubicle-vdo/xbmc-israel#432]
Dear Gents 

First Thank you for your work on the add-on and the live tv both works very well. 

I would like to inquire about the guide/info  language that is mostly in Hebrew I believe, is there a way to have it in French only for the French channels? 

Again thank you for your kind assistance. 

Alexandre

**Comment by avigdork** [comment]
The addon (like his name) intend for Israelis first.
It's not possible right now to maintain more than one EPG, maybe in the future.

**Comment by Alexuu** [comment]
Hi 

I hope you are well.

I would like to inquire about the French channels, do you have an issue recently as we only have 2 functioning? 

Thank you

Alexandre
