### ISSUE TITLE
IsraeLive: English EPG data option

### ISSUE THREAD

**Issue by zevnyc** [cubicle-vdo/xbmc-israel#435]
Hi Avigdor & Benny, you guys rock!
I use IsraeLive on every device and I've recommended it to so many others and the consensus is that it's the best live TV/PVR add-on yet. 
However I live in the US and although I speak Hebrew many people that use IsraeLive don't so if it's possible to add an option to leave EPG on English channels in English or add English info together with the Hebrew that'll be awesome.
Anther issue with Hebrew is the fonts, not always it's there an Arial based font available.
Thanx a lot for your hard work, the add-on has evolved nicely!

**Comment by Alexuu** [comment]
Hi guys, hope you are well...
Just a quick question, I tried several times to install israelive tv but I could not find the repo / addon. 
Is the addon closed ?
Thank you

**Comment by Alexuu** [comment]
I mean I have the xbmc Israeli streaming repo but I could not find the addon.
Thank you

**Comment by ghost** [comment]
Hi. 
The addon moved to my repo and the name changed to GlobeTV.

**Comment by Alexuu** [comment]
Thank you for your reply.
Are the French channel still available?

Alexandre

**Comment by Alexuu** [comment]
Sorry the French channel are gone but what a pleasure to reinstall the addon with automated pvr and eng...

I wish I could have my French back channels soon ;( 

Alexandre

**Comment by Alexuu** [comment]
Hi guys,

Are the French channels coming back any time soon? 

Thanks 

Alexandre
